###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
version: "3.1"
services:

    mysql:
      image: mysql
      container_name: docker-symfony4-mysql
      networks:
        - backend
      working_dir: /application
      volumes:
        - .:/application
      environment:
        - MYSQL_ROOT_PASSWORD=dbpw
        - MYSQL_DATABASE=pilotos
        - MYSQL_USER=root
        - MYSQL_PASSWORD=dbpw
      ports:
        - "3306:3306"
    

    phpmyadmin:
      depends_on:
       - mysql
      networks:
       - backend
      image: phpmyadmin/phpmyadmin
      ports:
       - "8080:80"
      environment:
       - PMA_HOST=mysql
       - PMA_PORT= 3306
      links:
       - mysql:db
   

    webserver:
      image: nginx:alpine

      container_name: docker-symfony4-webserver
      working_dir: /application
      volumes:
          - .:/application
          - ./phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
       - "8000:80"
      links:
       - mysql:db

    php-fpm:
      build: phpdocker/php-fpm
      networks:
       - backend
      depends_on:
       - phpmyadmin
      env_file:
          - ./.env
      container_name: docker-symfony4-php-fpm
      working_dir: /application
      volumes:
        - .:/application
        - ./phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/7.2/fpm/conf.d/99-overrides.ini
      links:
       - mysql:db
      
networks:
  backend:
 



 
 


















      


